resources:
  - ../../base/voice-bot

patches:
  - target:
      kind: Rollout
      name: voice-bot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dbag34/voice-bot-rollout:green
  - target:
      kind: Ingress
      name: voice-bot-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: voice-bot-dev.example.com