apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-bot
  template:
    metadata:
      labels:
        app: voice-bot
    spec:
      containers:
        - name: voice-bot
          image: nginx:latest
          ports:
            - containerPort: 80