apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-service
  namespace: argocd

spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          - env: dev
            namespace: my-service-dev
            path: overlays/dev

          - env: uat
            namespace: my-service-uat
            path: overlays/uat

          - env: cug
            namespace: my-service-cug
            path: overlays/cug

          - env: prod
            namespace: my-service-prod
            path: overlays/prod

  template:
    metadata:
      name: my-service-{{.env}}

    spec:
      project: default

      source:
        repoURL: https://github.com/Dbag34/config-repo.git
        targetRevision: main
        path: "{{.path}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true

        syncOptions:
          - CreateNamespace=true